### ISSUE TITLE
infamous-rule fails to build

### ISSUE THREAD

**Issue by falkTX** [ssj71/infamousPlugins#14] opened 2015-09-18 10:36 UTC
In src/rule.c you're using uint*_t types, but you do not include 'stdint.h' needed to use those.
This results in:

```
src/rule.c:4:16: error: unknown type name 'uint8_t'
 void ruleprint(uint8_t x)
                ^
src/rule.c:15:15: error: unknown type name 'uint32_t'
 void binprint(uint32_t x, uint8_t n)
               ^
src/rule.c:15:27: error: unknown type name 'uint8_t'
 void binprint(uint32_t x, uint8_t n)
                           ^
src/rule.c:44:20: error: unknown type name 'int8_t'
 int main(int argc, int8_t **argv)
```

Easy to fix:

```
--- infamous-plugins-0.1.1.orig/src/rule.c
+++ infamous-plugins-0.1.1/src/rule.c
@@ -1,5 +1,6 @@
 #include<unistd.h>
 #include<stdio.h>
+#include<stdint.h>

 void ruleprint(uint8_t x)
 {
```

**Comment by ssj71** [comment] 2015-09-18 15:18
Duplicate of #13. Already resolved in master. Thanks. And sorry about that.

**Closed as completed** 2015-09-18 15:18 UTC
