### ISSUE TITLE
Powercut crashing Ardour

### ISSUE THREAD

**Issue by unfa** [ssj71/infamousPlugins#24] opened 2016-09-18 18:32 UTC
I've recently was using The Infamous Powercut, and it started to crash my Ardour5 session every time I hit play.

Here's a backtrace from GDB:

```
(gdb) bt
#0  0x00007fffc55a7f55 in ?? () from /usr/lib/lv2/powercut.lv2/powercut.so
#1  0x00007ffff6a07385 in lilv_instance_run (instance=0xc5be260, sample_count=1) at /home/ardour/linux-x86_64-v5/gtk/inst/include/lilv-0/lilv/lilv.h:1662
#2  0x00007ffff6a1682a in ARDOUR::LV2Plugin::run (this=0xc58f980, nframes=1, sync_work=false) at ../libs/ardour/lv2_plugin.cc:2855
#3  0x00007ffff6a14534 in ARDOUR::LV2Plugin::connect_and_run (this=0xc58f980, bufs=..., start=3072, end=3073, speed=1, in_map=..., out_map=..., nframes=1, offset=0) at ../libs/ardour/lv2_plugin.cc:2524
#4  0x00007ffff67d87e5 in ARDOUR::PluginInsert::silence (this=0xc586410, nframes=1, start_frame=3072) at ../libs/ardour/plugin_insert.cc:1075
#5  0x00007ffff686f236 in ARDOUR::Route::silence_unlocked (this=0xc566890, nframes=1) at ../libs/ardour/route.cc:2889
#6  0x00007ffff69f3e61 in ARDOUR::Track::check_initial_delay (this=0xc566890, nframes=255, transport_frame=@0x7fffc68a6868: 3072) at ../libs/ardour/track.cc:1019
#7  0x00007ffff63eaba1 in ARDOUR::AudioTrack::roll (this=0xc566890, nframes=256, start_frame=3072, end_frame=3328, declick=0, need_butler=@0x7fffc68a68ff: false) at ../libs/ardour/audio_track.cc:364
#8  0x00007ffff6555aa1 in ARDOUR::Graph::process_one_route (this=0x4abfcf0, route=0xc566890) at ../libs/ardour/graph.cc:588
#9  0x00007ffff655b13a in ARDOUR::GraphNode::process (this=0xc566b98) at ../libs/ardour/graphnode.cc:79
#10 0x00007ffff6553f6f in ARDOUR::Graph::run_one (this=0x4abfcf0) at ../libs/ardour/graph.cc:400
#11 0x00007ffff655419e in ARDOUR::Graph::helper_thread (this=0x4abfcf0) at ../libs/ardour/graph.cc:418
#12 0x00007ffff655a765 in boost::_mfi::mf0<void, ARDOUR::Graph>::operator() (this=0x7fffc68a6d58, p=0x4abfcf0) at /home/ardour/linux-x86_64-v5/gtk/inst/include/boost/bind/mem_fn_template.hpp:49
#13 0x00007ffff6559e60 in boost::_bi::list1<boost::_bi::value<ARDOUR::Graph*> >::operator()<boost::_mfi::mf0<void, ARDOUR::Graph>, boost::_bi::list0> (this=0x7fffc68a6d68, f=..., a=...)
    at /home/ardour/linux-x86_64-v5/gtk/inst/include/boost/bind/bind.hpp:253
#14 0x00007ffff65592d3 in boost::_bi::bind_t<void, boost::_mfi::mf0<void, ARDOUR::Graph>, boost::_bi::list1<boost::_bi::value<ARDOUR::Graph*> > >::operator() (this=0x7fffc68a6d58)
    at /home/ardour/linux-x86_64-v5/gtk/inst/include/boost/bind/bind_template.hpp:20
#15 0x00007ffff6558b55 in boost::detail::function::void_function_obj_invoker0<boost::_bi::bind_t<void, boost::_mfi::mf0<void, ARDOUR::Graph>, boost::_bi::list1<boost::_bi::value<ARDOUR::Graph*> > >, void>::invoke
    (function_obj_ptr=...) at /home/ardour/linux-x86_64-v5/gtk/inst/include/boost/function/function_template.hpp:153
#16 0x0000000000730682 in boost::function0<void>::operator() (this=0x7fffc68a6d50) at /home/ardour/linux-x86_64-v5/gtk/inst/include/boost/function/function_template.hpp:760
#17 0x00007fffd6159c29 in ARDOUR::JACKAudioBackend::_start_process_thread (arg=0x4a0b960) at ../libs/backends/jack/jack_audiobackend.cc:936
#18 0x00007fffef6796fa in start_thread (arg=0x7fffc68a7700) at pthread_create.c:333
#19 0x00007fffec379b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

I was using Ardour 5.3 first the stable , then 5.3.128, 5.3.130 and finally the debug buld has helped me to find the plugin that caused the trouble.

**Comment by ssj71** [comment] 2016-09-19 16:14
Hmm, I haven't experienced this. but I haven't tried it since ardour 4 or so. I'll check it out as soon as I get a chance. Unfortunately your copy of the plugin doesn't have debug symbols so I can't tell exactly why it crashed.

**Comment by ssj71** [comment] 2016-09-21 17:01
ok, sorry it took me so long. I just built ardour from git this morning and tried it. I don't have any crash. Can you send me the session somehow? Or have you tried it in a different session?

**Comment by Joermungand** [comment] 2016-09-21 17:20
I cannot reproduce it, either – using Ardour 5 built from git (rev 
5.3-5-g0ff233d) on 64-bit Arch Linux.

**Comment by ssj71** [comment] 2017-01-25 20:13
closing, please reopen if it is still a problem.

**Closed as completed by ssj71** 2017-01-25 20:13 UTC
